In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')
import seaborn as sbn

from math import ceil

import scipy.stats as stats

import matplotlib.pyplot as plt

from pandas.plotting import scatter_matrix







import timeit
import datetime as dt

import pandasql as ps

In [8]:
jan = pd.read_csv('~/Desktop/capstone2/jan_scraped_temps.csv')
feb = pd.read_csv('~/Desktop/capstone2/feb_scraped_temps.csv')
march = pd.read_csv('~/Desktop/capstone2/march_scraped_temps.csv')
april = pd.read_csv('~/Desktop/capstone2/april_scraped_temps.csv')
may = pd.read_csv('~/Desktop/capstone2/may_scraped_temps.csv')
june = pd.read_csv('~/Desktop/capstone2/june_scraped_temps.csv')
july = pd.read_csv('~/Desktop/capstone2/july_scraped_temps.csv')
august = pd.read_csv('~/Desktop/capstone2/august_scraped_temps.csv')
september = pd.read_csv('~/Desktop/capstone2/september_scraped_temps.csv')
october = pd.read_csv('~/Desktop/capstone2/october_scraped_temps.csv')
november = pd.read_csv('~/Desktop/capstone2/november_scraped_temps.csv')
december = pd.read_csv('~/Desktop/capstone2/december_scraped_temps.csv')

#jan 1st & november 8th missing


In [9]:
month_lst = [jan, feb, march, april, may, june, july, august, september, october, november, december ]

In [10]:
dall_weather_2020 = pd.concat(month_lst)

In [13]:
dall_weather_2020['new_hour'] = dall_weather_2020[]

hour  temp   dew humidity wind_speed  pressure  precip          cloud
0     1:53 AM  54 F  42 F     64 %     13 mph  29.19 in  0.0 in         Cloudy
1     2:53 AM  54 F  44 F     69 %     13 mph  29.15 in  0.0 in         Cloudy
2     3:53 AM  54 F  44 F     69 %     16 mph  29.12 in  0.0 in         Cloudy
3     4:53 AM  54 F  46 F     75 %     10 mph  29.09 in  0.0 in         Cloudy
4     5:53 AM  53 F  46 F     77 %     10 mph  29.09 in  0.0 in         Cloudy
..        ...   ...   ...      ...        ...       ...     ...            ...
871   9:23 PM  42 F  39 F     89 %      3 mph  29.11 in  0.1 in     Light Rain
872   9:53 PM  41 F  38 F     89 %      9 mph  29.10 in  0.1 in     Light Rain
873  10:53 PM  40 F  38 F     93 %      9 mph  29.12 in  0.0 in  Light Drizzle
874  11:53 PM  39 F  37 F     93 %      8 mph  29.10 in  0.0 in  Light Drizzle
875  12:53 AM  39 F  37 F     93 %      7 mph  29.09 in  0.0 in  Light Drizzle

[10018 rows x 8 columns]

In [14]:
dall_weather_2020.cloud.value_counts()

Fair                       3250
Mostly Cloudy              2336
Cloudy                     2162
Partly Cloudy              1083
Light Rain                  450
Light Drizzle               139
Rain                         87
Light Rain with Thunder      85
Heavy T-Storm                75
Thunder                      56
Heavy Rain                   48
T-Storm                      42
Fog                          32
Cloudy / Windy               27
Mostly Cloudy / Windy        27
Haze                         26
Fair / Windy                 23
Partly Cloudy / Windy        15
Light Rain / Windy           13
Heavy T-Storm / Windy         8
Heavy Rain / Windy            7
Widespread Dust               5
Thunder and Hail              4
Thunder / Windy               3
Blowing Dust                  3
Patches of Fog                3
Blowing Dust / Windy          2
Fog / Windy                   2
Rain / Windy                  2
Haze / Windy                  1
Light Drizzle / Windy         1
Name: cl

In [16]:
hours = np.arange(0,24)
hours_3 = []
for i in range (365):
    
    hours_3.append(hours)
hours_3

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 

In [22]:
hours_df = pd.DataFrame(hours_3)
numpy_array = hours_df.to_numpy()
hours_col= numpy_array.reshape(8760, -1)
hours_final_df = pd.DataFrame(hours_col)

In [27]:
hours_final_df[2:7992]

0
2      2
3      3
4      4
5      5
6      6
...   ..
7987  19
7988  20
7989  21
7990  22
7991  23

[7990 rows x 1 columns]

In [33]:
 hours2 = hours_final_df[1:7992] #8760-768

In [34]:
dall_weather_2020['hours'] = hours2

In [36]:
dall_weather_2020[:30]

hour  temp   dew humidity wind_speed  pressure  precip          cloud  \
0    1:53 AM  54 F  42 F     64 %     13 mph  29.19 in  0.0 in         Cloudy   
1    2:53 AM  54 F  44 F     69 %     13 mph  29.15 in  0.0 in         Cloudy   
2    3:53 AM  54 F  44 F     69 %     16 mph  29.12 in  0.0 in         Cloudy   
3    4:53 AM  54 F  46 F     75 %     10 mph  29.09 in  0.0 in         Cloudy   
4    5:53 AM  53 F  46 F     77 %     10 mph  29.09 in  0.0 in         Cloudy   
5    6:53 AM  53 F  46 F     77 %     12 mph  29.08 in  0.0 in         Cloudy   
6    7:53 AM  54 F  47 F     77 %      9 mph  29.08 in  0.0 in  Mostly Cloudy   
7    8:53 AM  54 F  47 F     77 %      9 mph  29.09 in  0.0 in         Cloudy   
8    9:53 AM  55 F  47 F     74 %      7 mph  29.09 in  0.0 in  Mostly Cloudy   
9   10:53 AM  56 F  48 F     75 %      9 mph  29.11 in  0.0 in  Mostly Cloudy   
10  11:53 AM  59 F  48 F     67 %      0 mph  29.12 in  0.0 in  Mostly Cloudy   
11  12:53 PM  61 F  49 F     64 %      8 mph  29.08 in  0.0 in         Cloudy   
12   1:53 PM  61 F  49 F     64 %     10 mph  29.05 in  0.0 in         Cloudy   
13   2:53 PM  61 F  49 F     64 %     15 mph  29.03 in  0.0 in         Cloudy   
14   3:53 PM  62 F  49 F     62 %      7 mph  29.00 in  0.0 in         Cloudy   
15   4:53 PM  61 F  50 F     67 %      8 mph  29.02 in  0.0 in         Cloudy   
16   5:53 PM  60 F  50 F     69 %      7 mph  29.03 in  0.0 in  Mostly Cloudy   
17   6:53 PM  60 F  50 F     69 %      5 mph  29.03 in  0.0 in  Mostly Cloudy   
18   8:53 PM  57 F  50 F     77 %      6 mph  29.08 in  0.0 in           Fair   
19   9:53 PM  56 F  51 F     84 %      3 mph  29.10 in  0.0 in           Fair   
20  10:53 PM  55 F  50 F     83 %      3 mph  29.12 in  0.0 in           Fair   
21  11:53 PM  52 F  49 F     89 %      6 mph  29.13 in  0.0 in           Fair   
22  12:53 AM  50 F  47 F     89 %      0 mph  29.15 in  0.0 in           Fair   
23   1:53 AM  54 F  42 F     64 %     13 mph  29.19 in  0.0 in         Cloudy   
24   2:53 AM  54 F  44 F     69 %     13 mph  29.15 in  0.0 in         Cloudy   
25   3:53 AM  54 F  44 F     69 %     16 mph  29.12 in  0.0 in         Cloudy   
26   4:53 AM  54 F  46 F     75 %     10 mph  29.09 in  0.0 in         Cloudy   
27   5:53 AM  53 F  46 F     77 %     10 mph  29.09 in  0.0 in         Cloudy   
28   6:53 AM  53 F  46 F     77 %     12 mph  29.08 in  0.0 in         Cloudy   
29   7:53 AM  54 F  47 F     77 %      9 mph  29.08 in  0.0 in  Mostly Cloudy   

    hours  
0     NaN  
1     1.0  
2     2.0  
3     3.0  
4     4.0  
5     5.0  
6     6.0  
7     7.0  
8     8.0  
9     9.0  
10   10.0  
11   11.0  
12   12.0  
13   13.0  
14   14.0  
15   15.0  
16   16.0  
17   17.0  
18   18.0  
19   19.0  
20   20.0  
21   21.0  
22   22.0  
23   23.0  
24    0.0  
25    1.0  
26    2.0  
27    3.0  
28    4.0  
29    5.0

In [37]:
dall_weather2020['new_datetime'] = dall_weather_2020['hour'].to_datetime

AttributeError: 'Series' object has no attribute 'to_datetime'

In [39]:
dall_weather_2020['New_datetime'] = pd.to_datetime(dall_weather_2020['hour'],infer_datetime_format=True)

In [40]:
dall_weather_2020

hour  temp   dew humidity wind_speed  pressure  precip  \
0     1:53 AM  54 F  42 F     64 %     13 mph  29.19 in  0.0 in   
1     2:53 AM  54 F  44 F     69 %     13 mph  29.15 in  0.0 in   
2     3:53 AM  54 F  44 F     69 %     16 mph  29.12 in  0.0 in   
3     4:53 AM  54 F  46 F     75 %     10 mph  29.09 in  0.0 in   
4     5:53 AM  53 F  46 F     77 %     10 mph  29.09 in  0.0 in   
..        ...   ...   ...      ...        ...       ...     ...   
871   9:23 PM  42 F  39 F     89 %      3 mph  29.11 in  0.1 in   
872   9:53 PM  41 F  38 F     89 %      9 mph  29.10 in  0.1 in   
873  10:53 PM  40 F  38 F     93 %      9 mph  29.12 in  0.0 in   
874  11:53 PM  39 F  37 F     93 %      8 mph  29.10 in  0.0 in   
875  12:53 AM  39 F  37 F     93 %      7 mph  29.09 in  0.0 in   

             cloud  hours        New_datetime  
0           Cloudy    NaN 2021-03-18 01:53:00  
1           Cloudy    1.0 2021-03-18 02:53:00  
2           Cloudy    2.0 2021-03-18 03:53:00  
3           Cloudy    3.0 2021-03-18 04:53:00  
4           Cloudy    4.0 2021-03-18 05:53:00  
..             ...    ...                 ...  
871     Light Rain    7.0 2021-03-18 21:23:00  
872     Light Rain    8.0 2021-03-18 21:53:00  
873  Light Drizzle    9.0 2021-03-18 22:53:00  
874  Light Drizzle   10.0 2021-03-18 23:53:00  
875  Light Drizzle   11.0 2021-03-18 00:53:00  

[10018 rows x 10 columns]